apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jnrosale-carla-cache
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
